name: flutter_keyboard_visibility_web
description: An implementation for the web platform of `flutter_keyboard_visibility'
version: 3.0.0
homepage: https://gitlab.com/fittin/fittin-mobile/flutter_keyboard_visibility_web
repository: https://gitlab.com/fittin/fittin-mobile/flutter_keyboard_visibility_web


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPluginWeb
        fileName: flutter_keyboard_visibility_web.dart

dependencies:
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  web: 1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter